### ISSUE TITLE
Meta: improve code quality

### ISSUE THREAD

**Issue by federicobond** [ihameli/complexnets#15]
This is a meta issue to keep track of changes needed to improve code quality:

 * [ ] Fix build with Qt5
 * [ ] Fix most warnings thrown by the GCC compiler
 * [ ] Configure CI build system for building in Linux (bonus: OS X and AppVeyor for Windows)

Nice to have:

 * [ ] Use clang-format to maintain a consistent code style across the codebase
 * [ ] Fix compilation with Clang
